import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
import Footer from '../components/Footer'
import Head from 'next/head'
import React from 'react'
import Content from '../components/Content'
export default function Product() {
    return (
      <div>
        <Head>
          <title>Sprint3 - Product Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <Content />
        <Footer />
      </div>
    )
  }
  